[[Gearman]]
URL = "gearman:4730"

HostStatus = "statusngin_hoststatus"
HostCheck = "statusngin_hostchecks"
ServiceStatus = "statusngin_servicestatus"
ServiceCheck = "statusngin_servicechecks"
ServicePerfData = "statusngin_service_perfdata"
StateChange = "statusngin_statechanges"
AcknowledgementData = "statusngin_acknowledgements"
FlappingData = "statusngin_flappings"
DowntimeData = "statusngin_downtimes"
ContactNotificationMethodData = "statusngin_contactnotificationmethod"
RestartData = "statusngin_core_restart"
OCHP = "statusngin_ochp"
OCSP = "statusngin_ocsp"
WorkerCommand = "statusngin_cmd"
#WorkerOCHP = "statusngin_ochp"
#WorkerOCSP = "statusngin_ocsp"

SystemCommandData = "statusngin_systemcommands"
CommentData = "statusngin_comments"
ExternalCommandData = "statusngin_externalcommands"
NotificationData = "statusngin_notifications"
ProgramStatusData = "statusngin_programmstatus"
ContactStatusData = "statusngin_contactstatus"
ContactNotificationData = "statusngin_contactnotificationdata"
EventHandlerData = "statusngin_eventhandler"
ProcessData = "statusngin_processdata"
LogData = "statusngin_logentries"


[[Rabbitmq]]
Hostname = "rabbit"
Username = "statusengine"
Password = "statusengine"

HostStatus = "statusngin_hoststatus"
HostCheck = "statusngin_hostchecks"
ServiceStatus = "statusngin_servicestatus"
ServiceCheck = "statusngin_servicechecks"
ServicePerfData = "statusngin_service_perfdata"
StateChange = "statusngin_statechanges"
AcknowledgementData = "statusngin_acknowledgements"
FlappingData = "statusngin_flappings"
DowntimeData = "statusngin_downtimes"
ContactNotificationMethodData = "statusngin_contactnotificationmethod"
RestartData = "statusngin_core_restart"
OCHP = "statusngin_ochp"
OCSP = "statusngin_ocsp"
WorkerCommand = "statusngin_cmd"
#WorkerOCHP = "statusngin_ochp"
#WorkerOCSP = "statusngin_ocsp"

SystemCommandData = "statusngin_systemcommands"
CommentData = "statusngin_comments"
ExternalCommandData = "statusngin_externalcommands"
NotificationData = "statusngin_notifications"
ProgramStatusData = "statusngin_programmstatus"
ContactStatusData = "statusngin_contactstatus"
ContactNotificationData = "statusngin_contactnotificationdata"
EventHandlerData = "statusngin_eventhandler"
ProcessData = "statusngin_processdata"
LogData = "statusngin_logentries"

[Scheduler]
# Used to fix a nasty scheduler behaviour in naemon when you often restart naemon
# If next_schedule of a service or host is in the past during startup, we reschedule
# the service/host within $StartupScheduleMax seconds instead of the check_intervall of the host/service.
StartupScheduleMax = 30

[Bulk]
## Maximum number of messages in one bulk message
Maximum = 2
## Flush Bulk messages every X seconds dispite number of cached messages
FlushInterval = 5
## List of queue identifier which should be created as bulk message. This is a global option for all connections
Queues = ["HostStatus", "HostCheck", "ServiceStatus", "ServiceCheck", "ServicePerfData", "StateChange", "OCHP", "OCSP", "LogData"]
